version: '3.8'

services:
  backup:
    build: .
    container_name: backup-service
    restart: unless-stopped
    # Переменные окружения для секретов
    environment:
      # Укажи здесь свой токен, это безопаснее чем в config.yml
      - TELEGRAM_TOKEN=7223113612:AAFjnxyKhn_IE2AjkEmDLGxy2iMcGFSOgck
      # Пароль для rclone, если он зашифрован
      # - RCLONE_CONFIG_PASS=your_rclone_password
    volumes:
      # Подключаем папку с конфигом
      - ./config:/config
      # Подключаем папки, которые нужно бекапить (read-only для безопасности)
      - ./test:/test:ro